### ISSUE TITLE
Add PL-900 exam self assessment

### ISSUE THREAD

**Issue by gkerstens** [Build5Nines/exam-assessments#10]
[Exam: PL-900: Microsoft Power Platform Fundamentals](https://docs.microsoft.com/learn/certifications/exams/pl-900)
[Exam-Msft-PL-900-Self-Assessment.xlsx](https://github.com/Build5Nines/exam-assessments/files/3949654/Exam-Msft-PL-900-Self-Assessment.xlsx)

**Comment by crpietschmann** [comment]
Thanks for the suggestion, this one has been added!
