### ISSUE TITLE
Exam-Msft-AZ-220-Self-Assessment-Build5Nines.xlsx File Corrupt

### ISSUE THREAD

**Issue by iLikeAzureSQL** [Build5Nines/exam-assessments#13]
Can't open the Exam-Msft-AZ-220-Self-Assessment-Build5Nines.xlsx files
Excel Prompts as corrupt file

**Comment by crpietschmann** [comment]
I'm not seeing any issues with the file. Have you tried downloading it again, in case the download got corrupted? Also, if the issue persists, what version of Excel are you running?

**Comment by crpietschmann** [comment]
I have double checked the file download again, and there no problem with it I can see. Please try re-downloading the file again if you encounter this. Thanks!
