### ISSUE TITLE
Modify docs.microsoft.com links in assessments

### ISSUE THREAD

**Issue by themichaelbender** [Build5Nines/exam-assessments#8]
Consider removing /en-us/ from all links to docs.microsoft.com in all assessments. By removing this, it allows non-US users of exam assessments to see the linked pages in their local language.

Preferreded syntax example:
https://docs.microsoft.com/learn/certifications/exams/ms-500

**Comment by crpietschmann** [comment]
Thanks for the tip! 👍  I'll update things when I get a chance.

**Comment by crpietschmann** [comment]
Done in commit https://github.com/Build5Nines/exam-assessments/commit/3a67602479b37935151e415333a78c30a1422206
